### ISSUE TITLE
Adding ILN logo

### ISSUE THREAD

**Issue by siulynot** [VerusCoin/Agama#141]
Hello, we noticed that ILN coin is active in Verus Agama wallet but it has no logo. 

We have the logo here:

 https://github.com/chainmakers/EasyDEX-GUI/blob/dev/react/src/assets/images/cryptologo/btc/iln.png

We would appreaciate if it can be added in the next release, thanks.

**Comment by michaeltout** [comment]
Thanks for bringing this issue up, we added it in this push to EasyDEX-GUI and it will be included in the next release :). 

[https://github.com/VerusCoin/EasyDEX-GUI/commit/b9e7ad930790d5cb76a2ca6fc523eb13adda6639](url)
