### ISSUE TITLE
all my kmd sent away without me! please help

### ISSUE THREAD

**Issue by filav** [VerusCoin/Agama#159]
dear, i downloaded latest agama wallet, sent there my kmd, after a few minutes all these kmd transfered away without me, my balance is 0.
how is it possible??? please help

**Comment by michaeltout** [comment]
It appears that this issue isn't related to the Agama source code, and is being resolved on our discord, so I'll close this for now.

**Comment by filav** [comment]
You can add an warning to the agama wallet to protect users from using old
addresses that can be compromised...



s pozdravem

filip vávra




*efi design*  */*  *filip vávra*  */*  praha
grafika  */*  design  */*  foto  */*  audiovize
*e-mail *filipvavra@gmail.com  */*  *tel* +420 777 725 227
<+420%20777%20725%20227>
*ič* 68660171  */ * *dič* cz8008194524




Dne 10. listopadu 2019 v 21:35:16, Michael Toutonghi (
notifications@github.com) napsal/a:
