### ISSUE TITLE
Seed stolen/compromised from computer

### ISSUE THREAD

**Issue by billygll** [VerusCoin/Agama#178]
Hello -  Just checked my Agama Verus Wallet -- I had transferred 1280 KMD to it from the original Agama wallet after that hacking incident back in 2018. The 1280 coins  that I put in the new wallet to keep safe have been removed by someone unknown to me on March 14, 2020.
I believe I have been hacked and I don't know what to do to recover my coins. Can someone steer me in the right direction. I can provide all the information of the send transaction.
![image](https://user-images.githubusercontent.com/47426780/79141497-e983b000-7d87-11ea-9a7c-20c40103254c.png)

**Comment by michaeltout** [comment]
Hello, I am sorry to hear that your funds were likely stolen from your wallet. I would be happy to discuss this with you, and possibly provide help on our discord page here (https://discordapp.com/invite/VRKMP2S). However, please do not post issues of this type on our wallet GitHub page:

1) We maintain strict security protocols to ensure our wallets, and the people that use them, do not get compromised, and posting a generic loss of funds issue with the title "Agama Verus Hacked" is a very serious accusation to make. We are constantly probing our software for security vulnerabilities.

2) Verus Agama is no longer a supported Verus wallet. Although has an excellent safety record, it will no longer be receiving updates, and we recommend everyone in our community switches over to our currently active wallet, Verus Desktop (https://github.com/VerusCoin/Verus-Desktop).

I am michaeltoutjr on our discord, feel free to message me with more details and I will try to assist.
