### ISSUE TITLE
Seed Phrase not restoring my wallet

### ISSUE THREAD

**Issue by milesmag** [VerusCoin/Agama#182]
Recently installed Agama Verus wallet on a new computer. I select Lite, then KMD, but my wallet name does not come up. I then enter either the seed phrase or the password. Both give me access to a wallet with no name, a different public address than before, and no balances, or transactions. Any help would be greatly appreciated, Thank you

**Comment by michaeltout** [comment]
Hi, the Agama wallet is deprecated and has been replaced by https://github.com/VerusCoin/Verus-Desktop, I've now updated the readme to reflect this. If you encounter any issues with Verus Desktop, feel free to ask the community at https://verus.io/discord

**Comment by milesmag** [comment]
Thank you sir.
